repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
        stages: [commit]
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7.5
        stages: [commit]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        stages: [commit]
  - repo: local
    hooks:
    - id: flake8
      name: flake8
      entry: pipenv run pytest tests/test_linters.py::test_flake8
      language: system
      pass_filenames: false
      stages: [commit]
    - id: pylint
      name: pylint
      entry: pipenv run pytest tests/test_linters.py::test_pylint
      pass_filenames: false
      language: system
      stages: [commit]
    - id: pytest
      name: pytest
      entry: pipenv run pytest
      pass_filenames: false
      language: system
      stages: [push]
